apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: fddx7ruu3-nodejs
  janus-idp.io/tekton: fddx7ruu3-nodejs
  backstage.io/kubernetes-id: fddx7ruu3-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fddx7ruu3-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
